"""empty message

Revision ID: f5642ef50aa4
Revises: 
Create Date: 2017-03-21 16:20:24.217192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5642ef50aa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tablet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tablet_email'), 'tablet', ['email'], unique=True)
    op.create_index(op.f('ix_tablet_name'), 'tablet', ['name'], unique=True)
    op.create_index(op.f('ix_tablet_nickname'), 'tablet', ['nickname'], unique=True)
    op.drop_table('slow_log')
    op.drop_table('useraccount_requestcallback')
    op.drop_table('func')
    op.drop_table('help_category')
    op.drop_table('auth_user_groups')
    op.drop_table('social_auth_usersocialauth')
    op.drop_table('plugin')
    op.drop_table('columns_priv')
    op.drop_table('base_category')
    op.drop_table('useraccount_refundrequest')
    op.drop_table('useraccount_onetimepassword')
    op.drop_table('social_auth_association')
    op.drop_table('django_migrations')
    op.drop_table('base_city')
    op.drop_table('contest_contestparticipant')
    op.drop_table('auth_permission')
    op.drop_table('auction_dreambig')
    op.drop_table('celebrity_celebrityrating')
    op.drop_table('time_zone_transition')
    op.drop_table('help_relation')
    op.drop_table('contest_questionoption')
    op.drop_table('servers')
    op.drop_table('useraccount_gifteedocument')
    op.drop_table('contest_contest_charities')
    op.drop_table('useraccount_userdocument')
    op.drop_table('db')
    op.drop_table('celebrity_charity')
    op.drop_table('host')
    op.drop_table('proxies_priv')
    op.drop_table('social_auth_code')
    op.drop_table('event')
    op.drop_table('base_systemsetting')
    op.drop_table('help_topic')
    op.drop_table('useraccount_auctiongift')
    op.drop_table('ndb_binlog_index')
    op.drop_table('auction_auctionbid')
    op.drop_table('django_session')
    op.drop_table('Us')
    op.drop_table('migrate_version')
    op.drop_table('useraccount_discountcoupon')
    op.drop_table('proc')
    op.drop_table('django_content_type')
    op.drop_table('contest_scratchcard')
    op.drop_table('time_zone_transition_type')
    op.drop_table('auction_auction')
    op.drop_table('procs_priv')
    op.drop_table('time_zone_name')
    op.drop_table('table1')
    op.drop_table('useraccount_paymenttransaction')
    op.drop_table('celebrity_celebrity_charities')
    op.drop_table('auction_auction_charities')
    op.drop_table('auth_group')
    op.drop_table('contest_contest')
    op.drop_table('base_documenttype')
    op.drop_table('tables_priv')
    op.drop_table('contest_contestpayment')
    op.drop_table('celebrity_celebrity')
    op.drop_table('useraccount_useraccount')
    op.drop_table('contest_contestquestion')
    op.drop_table('time_zone')
    op.drop_table('auth_group_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_table('base_country')
    op.drop_table('use')
    op.drop_table('django_admin_log')
    op.drop_table('time_zone_leap_second')
    op.drop_table('auth_user')
    op.drop_table('help_keyword')
    op.drop_table('social_auth_nonce')
    op.drop_table('Test')
    op.drop_table('user')
    op.drop_table('tab')
    op.drop_table('us')
    op.drop_table('general_log')
    op.drop_table('useraccount_usergiftee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useraccount_usergiftee',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=75), nullable=False),
    sa.Column('mobile_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='useraccount_usergiftee_user_id_3793c97f2e59861d_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('general_log',
    sa.Column('event_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_host', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('thread_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('server_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('command_type', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('argument', mysql.MEDIUMTEXT(), nullable=False),
    mysql_comment='General log',
    mysql_default_charset='utf8',
    mysql_engine='CSV'
    )
    op.create_table('us',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('root', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tab',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('Password', mysql.CHAR(charset='latin1', collation='latin1_bin', length=41), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Reload_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Shutdown_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Process_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('File_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_db_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Super_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Repl_slave_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Repl_client_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_user_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Event_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tablespace_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('ssl_type', mysql.ENUM('', 'ANY', 'X509', 'SPECIFIED', charset='utf8'), server_default=sa.text("''"), nullable=False),
    sa.Column('ssl_cipher', sa.BLOB(), nullable=False),
    sa.Column('x509_issuer', sa.BLOB(), nullable=False),
    sa.Column('x509_subject', sa.BLOB(), nullable=False),
    sa.Column('max_questions', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_updates', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_connections', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_user_connections', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('plugin', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=True),
    sa.Column('authentication_string', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.PrimaryKeyConstraint('Host', 'User'),
    mysql_collate='utf8_bin',
    mysql_comment='Users and global privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('Test',
    sa.Column('parent_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('root', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('parent_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('social_auth_nonce',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('server_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('salt', mysql.VARCHAR(length=65), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('help_keyword',
    sa.Column('help_keyword_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('help_keyword_id'),
    mysql_comment='help keywords',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('auth_user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=False),
    sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=75), nullable=False),
    sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date_joined', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('time_zone_leap_second',
    sa.Column('Transition_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('Correction', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Transition_time'),
    mysql_comment='Leap seconds information for time zones',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('django_admin_log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('action_time', mysql.DATETIME(), nullable=False),
    sa.Column('object_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('object_repr', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('action_flag', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('change_message', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='djang_content_type_id_697914295151027a_fk_django_content_type_id'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_52fdd58701c5f563_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('use',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('root', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('base_country',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_user_user_permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_u_permission_id_384b62483d7071f0_fk_auth_permission_id'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissi_user_id_7f0938558328534a_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_group_permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permission_group_id_689710a9a73b7457_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group__permission_id_1f49ccbbdc69d2fc_fk_auth_permission_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('time_zone',
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('Use_leap_seconds', mysql.ENUM('Y', 'N'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id'),
    mysql_comment='Time zones',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('contest_contestquestion',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('question', mysql.LONGTEXT(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('contest_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest_contest.id'], name='contest_contes_contest_id_5a67bbaded3eb763_fk_contest_contest_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('useraccount_useraccount',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('amount', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('is_screened', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_otp_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('mobile_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('address_line1', mysql.LONGTEXT(), nullable=True),
    sa.Column('address_line2', mysql.LONGTEXT(), nullable=True),
    sa.Column('city', mysql.LONGTEXT(), nullable=True),
    sa.Column('pincode', mysql.LONGTEXT(), nullable=True),
    sa.Column('state', mysql.LONGTEXT(), nullable=True),
    sa.Column('citizenship', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('date_of_birth', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('fwv_balance', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='useraccount_useraccount_user_id_6da3d116970d7d95_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('celebrity_celebrity',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('picture', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('celebrity_url', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('featured', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('description', mysql.LONGTEXT(), nullable=False),
    sa.Column('rating_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.CHAR(length=1), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['base_category.id'], name='celebrity_celeb_category_id_40d8f883cf7cb3bc_fk_base_category_id'),
    sa.ForeignKeyConstraint(['rating_id'], ['celebrity_celebrityrating.id'], name='celeb_rating_id_677bbe397ad1c069_fk_celebrity_celebrityrating_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('contest_contestpayment',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('payment_method', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('payment_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('object_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('contest_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('contest_participant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='conte_content_type_id_63cbb3d5cbb73e5d_fk_django_content_type_id'),
    sa.ForeignKeyConstraint(['contest_id'], ['contest_contest.id'], name='contest_contes_contest_id_4a2577f4ad1fb0de_fk_contest_contest_id'),
    sa.ForeignKeyConstraint(['contest_participant_id'], ['contest_contestparticipant.id'], name='D9d09641da6553b82c553797830071a4'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='contest_contestpayment_user_id_4ea0a4d946fe5300_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tables_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('Table_name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Grantor', mysql.CHAR(collation='utf8_bin', length=77), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('Table_priv', mysql.SET(charset='utf8', length=11), server_default=sa.text("''"), nullable=False),
    sa.Column('Column_priv', mysql.SET(charset='utf8', length=10), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User', 'Table_name'),
    mysql_collate='utf8_bin',
    mysql_comment='Table privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('base_documenttype',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('contest_contest',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('description', mysql.LONGTEXT(), nullable=False),
    sa.Column('thumbnail', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('donation_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('donation_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('reserve_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('start_date', mysql.DATETIME(), nullable=True),
    sa.Column('end_date', mysql.DATETIME(), nullable=True),
    sa.Column('draw_date', mysql.DATETIME(), nullable=True),
    sa.Column('celebrity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('hide_destination', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('hide_source', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('hide_travel_date', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('hide_travel_time', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('location_from_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('location_to_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('time_from', mysql.TIME(), nullable=True),
    sa.Column('time_to', mysql.TIME(), nullable=True),
    sa.Column('travel_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrity_celebrity.id'], name='contest__celebrity_id_518f332cebe4b016_fk_celebrity_celebrity_id'),
    sa.ForeignKeyConstraint(['location_from_id'], ['base_city.id'], name='contest_contest_location_from_id_ee9fde58651253f_fk_base_city_id'),
    sa.ForeignKeyConstraint(['location_to_id'], ['base_city.id'], name='contest_contest_location_to_id_74a98b293e7926cc_fk_base_city_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_group',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('auction_auction_charities',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('auction_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('charity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auction_auction.id'], name='auction_auctio_auction_id_71c057ed1f727e7d_fk_auction_auction_id'),
    sa.ForeignKeyConstraint(['charity_id'], ['celebrity_charity.id'], name='auction_auct_charity_id_7e36776427f2ac78_fk_celebrity_charity_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('celebrity_celebrity_charities',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('celebrity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('charity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrity_celebrity.id'], name='celebrit_celebrity_id_293c9a952b9653c1_fk_celebrity_celebrity_id'),
    sa.ForeignKeyConstraint(['charity_id'], ['celebrity_charity.id'], name='celebrity_ce_charity_id_423a9d6c939bab84_fk_celebrity_charity_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('useraccount_paymenttransaction',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('original_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('bank_transaction_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('transaction_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('payment_mode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('transaction_message', mysql.LONGTEXT(), nullable=True),
    sa.Column('payment_via', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('citrus_transaction_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cheque_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('reciept_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('other_details', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('paytm_transaction_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('balance', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('transaction_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('discount_coupon_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['discount_coupon_id'], ['useraccount_discountcoupon.id'], name='D786e31da46dc2a5cc611e1ed1297d06'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='useraccount_paymenttran_user_id_5455edb13e7c3ca2_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('table1',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('time_zone_name',
    sa.Column('Name', mysql.CHAR(length=64), nullable=False),
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Name'),
    mysql_comment='Time zone names',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('procs_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('Routine_name', mysql.CHAR(charset='utf8', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Routine_type', mysql.ENUM('FUNCTION', 'PROCEDURE', collation='utf8_bin'), nullable=False),
    sa.Column('Grantor', mysql.CHAR(collation='utf8_bin', length=77), server_default=sa.text("''"), nullable=False),
    sa.Column('Proc_priv', mysql.SET(charset='utf8', length=13), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User', 'Routine_name', 'Routine_type'),
    mysql_collate='utf8_bin',
    mysql_comment='Procedure privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('auction_auction',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('thumbnail', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('travel_date', sa.DATE(), nullable=True),
    sa.Column('time_from', mysql.TIME(), nullable=True),
    sa.Column('time_to', mysql.TIME(), nullable=True),
    sa.Column('active_from', mysql.DATETIME(), nullable=True),
    sa.Column('active_to', mysql.DATETIME(), nullable=True),
    sa.Column('hide_source', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('hide_destination', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('hide_travel_date', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('minimum_bid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('minimum_increment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('increment_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('celebrity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('location_from_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('location_to_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hide_travel_time', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('message1', mysql.LONGTEXT(), nullable=False),
    sa.Column('message2', mysql.LONGTEXT(), nullable=False),
    sa.Column('final_round_time_in_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('winner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrity_celebrity.id'], name='auction__celebrity_id_6d260f42e37ebd26_fk_celebrity_celebrity_id'),
    sa.ForeignKeyConstraint(['location_from_id'], ['base_city.id'], name='auction_auctio_location_from_id_5d592f31c3972f75_fk_base_city_id'),
    sa.ForeignKeyConstraint(['location_to_id'], ['base_city.id'], name='auction_auction_location_to_id_10744abb82df55c8_fk_base_city_id'),
    sa.ForeignKeyConstraint(['winner_id'], ['auction_auctionbid.id'], name='auction_auct_winner_id_77bcfd1d94aa5a77_fk_auction_auctionbid_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('time_zone_transition_type',
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Transition_type_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Offset', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Is_DST', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Abbreviation', mysql.CHAR(length=8), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id', 'Transition_type_id'),
    mysql_comment='Time zone transition types',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('contest_scratchcard',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('scratch_code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('contest_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('used_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest_contest.id'], name='contest_scratc_contest_id_4c568b008486b46b_fk_contest_contest_id'),
    sa.ForeignKeyConstraint(['used_by_id'], ['auth_user.id'], name='contest_scratchcard_used_by_id_292314a77c772c92_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('django_content_type',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('app_label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('proc',
    sa.Column('db', mysql.CHAR(charset='utf8', collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('type', mysql.ENUM('FUNCTION', 'PROCEDURE'), nullable=False),
    sa.Column('specific_name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('language', mysql.ENUM('SQL'), server_default=sa.text("'SQL'"), nullable=False),
    sa.Column('sql_data_access', mysql.ENUM('CONTAINS_SQL', 'NO_SQL', 'READS_SQL_DATA', 'MODIFIES_SQL_DATA'), server_default=sa.text("'CONTAINS_SQL'"), nullable=False),
    sa.Column('is_deterministic', mysql.ENUM('YES', 'NO'), server_default=sa.text("'NO'"), nullable=False),
    sa.Column('security_type', mysql.ENUM('INVOKER', 'DEFINER'), server_default=sa.text("'DEFINER'"), nullable=False),
    sa.Column('param_list', sa.BLOB(), nullable=False),
    sa.Column('returns', mysql.LONGBLOB(), nullable=False),
    sa.Column('body', mysql.LONGBLOB(), nullable=False),
    sa.Column('definer', mysql.CHAR(charset='utf8', collation='utf8_bin', length=77), server_default=sa.text("''"), nullable=False),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('sql_mode', mysql.SET(length=26), server_default=sa.text("''"), nullable=False),
    sa.Column('comment', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=False),
    sa.Column('character_set_client', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('collation_connection', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('db_collation', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('body_utf8', mysql.LONGBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('db', 'name', 'type'),
    mysql_comment='Stored Procedures',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('useraccount_discountcoupon',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('coupon', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('value_type', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('usage_times', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('migrate_version',
    sa.Column('repository_id', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', mysql.TEXT(), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Us',
    sa.Column('parent_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('root', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('parent_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('django_session',
    sa.Column('session_key', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', mysql.LONGTEXT(), nullable=False),
    sa.Column('expire_date', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('session_key'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('auction_auctionbid',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('current_bid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('maximum_bid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('auction_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('has_payed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auction_auction.id'], name='auction_auctio_auction_id_585aa84b857a13ae_fk_auction_auction_id'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auction_auctionbid_user_id_1563d9a113b0bf7f_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ndb_binlog_index',
    sa.Column('Position', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('File', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('epoch', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('inserts', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('updates', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('deletes', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('schemaops', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('epoch'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('useraccount_auctiongift',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('auction_bid_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('giftee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['auction_bid_id'], ['auction_auctionbid.id'], name='useracc_auction_bid_id_53435798bd07b527_fk_auction_auctionbid_id'),
    sa.ForeignKeyConstraint(['giftee_id'], ['useraccount_usergiftee.id'], name='useracco_giftee_id_1669a3b5f5bedd33_fk_useraccount_usergiftee_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('help_topic',
    sa.Column('help_topic_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.Column('help_category_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('example', mysql.TEXT(), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('help_topic_id'),
    mysql_comment='help topics',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('base_systemsetting',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('service_tax', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('bid_leverage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('event',
    sa.Column('db', mysql.CHAR(charset='utf8', collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('body', mysql.LONGBLOB(), nullable=False),
    sa.Column('definer', mysql.CHAR(charset='utf8', collation='utf8_bin', length=77), server_default=sa.text("''"), nullable=False),
    sa.Column('execute_at', mysql.DATETIME(), nullable=True),
    sa.Column('interval_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('interval_field', mysql.ENUM('YEAR', 'QUARTER', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'WEEK', 'SECOND', 'MICROSECOND', 'YEAR_MONTH', 'DAY_HOUR', 'DAY_MINUTE', 'DAY_SECOND', 'HOUR_MINUTE', 'HOUR_SECOND', 'MINUTE_SECOND', 'DAY_MICROSECOND', 'HOUR_MICROSECOND', 'MINUTE_MICROSECOND', 'SECOND_MICROSECOND'), nullable=True),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('last_executed', mysql.DATETIME(), nullable=True),
    sa.Column('starts', mysql.DATETIME(), nullable=True),
    sa.Column('ends', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.ENUM('ENABLED', 'DISABLED', 'SLAVESIDE_DISABLED'), server_default=sa.text("'ENABLED'"), nullable=False),
    sa.Column('on_completion', mysql.ENUM('DROP', 'PRESERVE'), server_default=sa.text("'DROP'"), nullable=False),
    sa.Column('sql_mode', mysql.SET(length=26), server_default=sa.text("''"), nullable=False),
    sa.Column('comment', mysql.CHAR(charset='utf8', collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('originator', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('time_zone', mysql.CHAR(charset='latin1', length=64), server_default=sa.text("'SYSTEM'"), nullable=False),
    sa.Column('character_set_client', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('collation_connection', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('db_collation', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('body_utf8', mysql.LONGBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('db', 'name'),
    mysql_comment='Events',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('social_auth_code',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=75), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('proxies_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('Proxied_host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Proxied_user', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('With_grant', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Grantor', mysql.CHAR(collation='utf8_bin', length=77), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User', 'Proxied_host', 'Proxied_user'),
    mysql_collate='utf8_bin',
    mysql_comment='User proxy privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('host',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db'),
    mysql_collate='utf8_bin',
    mysql_comment='Host privileges;  Merged with database privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('celebrity_charity',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('date_of_establishment', mysql.DATETIME(), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=75), nullable=True),
    sa.Column('mobile_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('picture', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('db',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Event_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User'),
    mysql_collate='utf8_bin',
    mysql_comment='Database privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('useraccount_userdocument',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('document', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('document_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['base_documenttype.id'], name='userac_document_type_id_14a17c7840a0b302_fk_base_documenttype_id'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='useraccount_userdocumen_user_id_4bbaa24486be113c_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('contest_contest_charities',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('contest_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('charity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['charity_id'], ['celebrity_charity.id'], name='contest_cont_charity_id_1fba6e99f2ce78b4_fk_celebrity_charity_id'),
    sa.ForeignKeyConstraint(['contest_id'], ['contest_contest.id'], name='contest_contes_contest_id_3bc4207e2e1ed744_fk_contest_contest_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('useraccount_gifteedocument',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('document', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('document_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('giftee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['base_documenttype.id'], name='useracc_document_type_id_edd28362d3169ad_fk_base_documenttype_id'),
    sa.ForeignKeyConstraint(['giftee_id'], ['useraccount_usergiftee.id'], name='useracco_giftee_id_64819a0d49a53c68_fk_useraccount_usergiftee_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('servers',
    sa.Column('Server_name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Host', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Username', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Password', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Port', mysql.INTEGER(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Socket', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Wrapper', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Owner', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Server_name'),
    mysql_comment='MySQL Foreign Servers table',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('contest_questionoption',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('option', mysql.LONGTEXT(), nullable=False),
    sa.Column('is_correct', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['contest_contestquestion.id'], name='conte_question_id_2ac26f10d6f621f8_fk_contest_contestquestion_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('help_relation',
    sa.Column('help_topic_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('help_keyword_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('help_keyword_id', 'help_topic_id'),
    mysql_comment='keyword-topic relation',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('time_zone_transition',
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Transition_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('Transition_type_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id', 'Transition_time'),
    mysql_comment='Time zone transitions',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('celebrity_celebrityrating',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('rating_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('rating_value', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('auction_dreambig',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('celebrity', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('maximum_bid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auction_dreambig_user_id_15ceb700f735ffb8_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_permission',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('codename', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth__content_type_id_508cf46651277a81_fk_django_content_type_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('contest_contestparticipant',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('number_of_chances', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quiz_taken', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_winner', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('contest_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_selected', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest_contest.id'], name='contest_contes_contest_id_473af8d40d8df007_fk_contest_contest_id'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='contest_contestparticip_user_id_18dd1229d3cb5b63_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('base_city',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('has_airport', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('country_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['base_country.id'], name='base_city_country_id_2336b5b8fc8cfe4d_fk_base_country_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('django_migrations',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('app', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('applied', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('social_auth_association',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('server_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('handle', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('secret', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('issued', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('lifetime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('assoc_type', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('useraccount_onetimepassword',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('scode', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('expiry_date', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='useraccount_onetimepass_user_id_3f1a85549781ad8f_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('useraccount_refundrequest',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('refund_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('refund_status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('payment_transaction_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('refunded_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('has_processed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['useraccount_paymenttransaction.id'], name='D7388a164a05e28a560a882e5544280e'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='useraccount_refundreque_user_id_35733e3ce4c8b3f4_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('base_category',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('columns_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('Table_name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Column_name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('Column_priv', mysql.SET(charset='utf8', length=10), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User', 'Table_name', 'Column_name'),
    mysql_collate='utf8_bin',
    mysql_comment='Column privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('plugin',
    sa.Column('name', mysql.VARCHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('dl', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_comment='MySQL plugins',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('social_auth_usersocialauth',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('provider', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('uid', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('extra_data', mysql.LONGTEXT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='social_auth_usersociala_user_id_193b2d80880502b2_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_user_groups',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_33ac548dcf5f8e37_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_4b5ed4ffdb8fd9b0_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('help_category',
    sa.Column('help_category_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.Column('parent_category_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('help_category_id'),
    mysql_comment='help categories',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('func',
    sa.Column('name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('ret', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('dl', mysql.CHAR(collation='utf8_bin', length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('type', mysql.ENUM('function', 'aggregate', charset='utf8'), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_collate='utf8_bin',
    mysql_comment='User defined functions',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('useraccount_requestcallback',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=False),
    sa.Column('mobile_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('have_called', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='useraccount_requestcall_user_id_26bb18c975b7acb9_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('slow_log',
    sa.Column('start_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_host', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('query_time', mysql.TIME(), nullable=False),
    sa.Column('lock_time', mysql.TIME(), nullable=False),
    sa.Column('rows_sent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('rows_examined', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('db', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('last_insert_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('insert_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('server_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sql_text', mysql.MEDIUMTEXT(), nullable=False),
    mysql_comment='Slow log',
    mysql_default_charset='utf8',
    mysql_engine='CSV'
    )
    op.drop_index(op.f('ix_tablet_nickname'), table_name='tablet')
    op.drop_index(op.f('ix_tablet_name'), table_name='tablet')
    op.drop_index(op.f('ix_tablet_email'), table_name='tablet')
    op.drop_table('tablet')
    # ### end Alembic commands ###
